name: CI/CD with Kubernetes

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: royjannessimbolon

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./be
          file: ./be/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/backend-express:latest
            ${{ env.DOCKER_USERNAME }}/backend-express:${{ github.sha }}

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./fe
          file: ./fe/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/frontend-vite:latest
            ${{ env.DOCKER_USERNAME }}/frontend-vite:${{ github.sha }}

      - name: Image digest
        run: |
          echo "Backend Image: ${{ env.DOCKER_USERNAME }}/backend-express:latest"
          echo "Backend SHA: ${{ env.DOCKER_USERNAME }}/backend-express:${{ github.sha }}"
          echo "Frontend Image: ${{ env.DOCKER_USERNAME }}/frontend-vite:latest"
          echo "Frontend SHA: ${{ env.DOCKER_USERNAME }}/frontend-vite:${{ github.sha }}"
          echo "sha=${{ github.sha }}" >> $GITHUB_OUTPUT
        id: build

  # Trigger Kubernetes update via webhook
  trigger-k8s-update:
    runs-on: ubuntu-latest
    needs: build-and-push
    
    steps:
      - name: Trigger Local Kubernetes Update
        run: 