apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: supply-chain-app
type: Opaque
stringData:
  database-url: "postgresql://postgres:Welawe01@host.docker.internal:5432/CRUDAPIII?schema=public"
  jwt-secret: "secret_inventory_jwt"
  vite-api-url: "http://backend-service:3000"
  base-url: "http://backend-service:3000/api/orders"