name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Backend
      - name: Build backend
        run: |
          docker buildx build --platform linux/amd64 \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/be:latest \
            ./be \
            --load

      - name: Push backend
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/be:latest

      # Frontend
      - name: Build frontend
        run: |
          docker buildx build --platform linux/amd64 \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/fe:latest \
            ./fe \
            --load

      - name: Push frontend
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fe:latest
